---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-operator
  namespace: argocd
spec:
  project: default
  sources:
    - chart: vault-secrets-operator
      repoURL: https://helm.releases.hashicorp.com
      targetRevision: 0.8.1
      helm:
        releaseName: vault-secrets-operator
        valueFiles:
          - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ServerSideApply=true
